# Generated by Django 4.2.7 on 2023-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=50, verbose_name='Name')),
                ('message_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message_note', models.CharField(max_length=600, verbose_name='Note')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
