# Generated by Django 4.2.7 on 2023-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_about_me_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(blank=True, max_length=600, verbose_name='About Me'),
        ),
    ]
