# Generated by Django 4.2.7 on 2023-11-19 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid?')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Order Total Price')),
                ('order_status', models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid'), ('c', 'Canceled')], default='u', max_length=10, verbose_name='Order Status')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('city', models.CharField(choices=[('teh', 'Tehran'), ('shz', 'Shiraz'), ('esf', 'Esfahan')], default='teh', max_length=3, verbose_name='City')),
                ('address', models.CharField(max_length=400, verbose_name='Address')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Order Notes')),
                ('zarinpal_authority', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal Authority')),
                ('zarinpal_ref_id', models.CharField(blank=True, max_length=255, verbose_name='Zarinpal Ref ID')),
                ('zarinpal_text', models.TextField(blank=True, max_length=700, verbose_name='Zarinpal Response Data')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('datetime_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('guarantee', models.CharField(max_length=2, verbose_name='Guarantee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Product')),
            ],
        ),
    ]
