# Generated by Django 4.2.7 on 2023-11-18 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(verbose_name='Discount')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ng', 'No Guarantee'), ('1y', '1 Years Guarantee'), ('2y', '2 Years Guarantee'), ('3y', '3 Years Guarantee')], default='ng', max_length=2, verbose_name='Name')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('features', models.JSONField()),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('inventory', models.PositiveIntegerField(verbose_name='Inventory')),
                ('active', models.BooleanField(default=True, verbose_name='Show In List')),
                ('slug', models.SlugField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Category')),
                ('colors', models.ManyToManyField(blank=True, to='products.color', verbose_name='Colors')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.company', verbose_name='Company')),
                ('discounts', models.ManyToManyField(blank=True, to='products.discount', verbose_name='Discounts')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag Name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=700, verbose_name='Review Text')),
                ('stars', models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=1, verbose_name='Stars')),
                ('active', models.BooleanField(default=False, verbose_name='Show')),
                ('recommend', models.BooleanField(default=True, verbose_name='Recommend')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, verbose_name='Comment Text')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('a', 'Approved'), ('na', 'Not Approved')], default='w', max_length=2, verbose_name='Status')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='products.product', verbose_name='Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='top_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='Top Product'),
        ),
    ]
