# Generated by Django 4.2.7 on 2023-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
